/**
 * Created by ltp on 2016/3/9.
 */
var word =[ [
     {"size": 31, "color": "#8dd3c7","text": "word"},
    { "size": 24, "color": "#ffffb3","text": "alright" },
    { "size": 13, "color": "#bebada","text": "hello" },
    { "size": 10, "color": "#80b1d3","text": "retrieve" },
    { "size": 24, "color": "#fb8072","text": "sprite" },
    { "size": 14, "color": "#fdb462","text": "previously" },
    { "size": 12, "color": "#b3de69","text": "separately" },
    { "size": 12, "color": "#fccde5","text": "layout" },
    { "size": 10, "color": "#d9d9d9","text": "area" },
    { "size": 5, "color": "#bc80bd","text": "comparing" },
    { "size": 5, "color": "#bc80bd","text": "comparing" },
    { "size": 5, "color": "#bc80bd","text": "comparing" }
],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],
    [
        [ {"size": 31, "color": "#8dd3c7","text": "word"},
            { "size": 24, "color": "#ffffb3","text": "alright" }],
        [{ "size": 13, "color": "#bebada","text": "hello" },
            { "size": 10, "color": "#80b1d3","text": "retrieve" }],
        [{ "size": 24, "color": "#fb8072","text": "sprite" },
            { "size": 14, "color": "#fdb462","text": "previously" }],
        [{ "size": 12, "color": "#b3de69","text": "separately" },
            { "size": 12, "color": "#fccde5","text": "layout" }],
        [{ "size": 10, "color": "#d9d9d9","text": "area" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }],
        [{ "size": 5, "color": "#bc80bd","text": "comparing" },
            { "size": 5, "color": "#bc80bd","text": "comparing" }]
    ],

];
var adju = [
    [],
    [[0,0],[-25,20],[-50,40],[-75,60],[-100,80],[-125,120],[-150,150]],
    [[0,0],[-17,12],[-34,24],[-51,36],[-67,48],[-85,60],[-100,72]],
    [[0,0],[-17,12],[-34,24],[-51,36],[-67,48],[-85,60],[-100,72]],


];